name: Main workflow
on:
  push:
    branches:
      - main
      - dev
jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup PostgreSQL 16
      run: |
        # Добавление репозитория PostgreSQL
        sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
        sudo apt-get update
        
        # Установка PostgreSQL 16
        sudo apt-get install -y postgresql-16
        
        # Запуск сервера PostgreSQL
        sudo systemctl start postgresql
        
        # Создание базы данных и пользователя
        sudo -u postgres psql -c "CREATE DATABASE ${{ secrets.DB_NAME || 'store' }};"
        sudo -u postgres psql -c "CREATE USER ${{ secrets.DB_USER || 'autotest' }} WITH PASSWORD '${{ secrets.DB_PASSWORD || 'autotest_password' }}';"
        sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE ${{ secrets.DB_NAME || 'store' }} TO ${{ secrets.DB_USER || 'autotest' }};"
        sudo -u postgres psql -d ${{ secrets.DB_NAME || 'store' }} -c "GRANT ALL PRIVILEGES ON SCHEMA public TO ${{ secrets.DB_USER || 'autotest' }};"
        sudo -u postgres psql -d ${{ secrets.DB_NAME || 'store' }} -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO ${{ secrets.DB_USER || 'autotest' }};"
        sudo -u postgres psql -d ${{ secrets.DB_NAME || 'store' }} -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO ${{ secrets.DB_USER || 'autotest' }};"

    #### Добавьте шаг с Flyway-миграциями
    - name: Run Flyway migrations
      uses: docker://flyway/flyway:9.22
      with:
        args: -url=jdbc:postgresql://${{ secrets.DB_HOST || 'localhost' }}:${{ secrets.DB_PORT || '5432' }}/${{ secrets.DB_NAME || 'store' }} -user=${{ secrets.DB_USER || 'autotest' }} -password=${{ secrets.DB_PASSWORD || 'autotest_password' }} -connectRetries=10 migrate
      env:
        FLYWAY_VALIDATE_MIGRATION_NAMING: "true"
        FLYWAY_LOCATIONS: "filesystem:./migrations"

    ### Этот шаг оставьте без изменений
    - name: Download and setup autotests binaries
      run: |
        wget -qO- cloud-services-engineer.gitlab.yandexcloud.net/practicum-cloud-services/dbops-autotests/-/package_files/1/download > dbopstest
        chmod +x ./dbopstest
        mv ./dbopstest /usr/local/bin/dbopstest

    ### Этот шаг оставьте без изменений
    - name: Test
      run: |
        dbopstest \
          -test.v \
          -host=${{ secrets.DB_HOST }} \
          -port=${{ secrets.DB_PORT }} \
          -user=${{ secrets.DB_USER }} \
          -password=${{ secrets.DB_PASSWORD }} \
          -db=${{ secrets.DB_NAME }}
